apiVersion: v1
kind: Service
metadata:
  name: nodejs-ex
  namespace: janine-dev
  labels:
    app: nodejs-ex
spec:
  selector:
    app: nodejs-ex
  ports:
  - name: http
    port: 8080
    targetPort: 8080
    protocol: TCP
  type: ClusterIP
